title: OverShifted's Blog
url: "https://overshifted.github.io"

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier

jekyll-minifier:
  exclude:
    - feed.xml
    - assets/js/*

google_analytics: G-2Q1PYDFXNX
